# Generated by Django 4.1.2 on 2022-10-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("React", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users", old_name="UserId", new_name="userId",
        ),
        migrations.RenameField(
            model_name="users", old_name="UserName", new_name="userName",
        ),
        migrations.AddField(
            model_name="users",
            name="Password",
            field=models.CharField(default="", max_length=100),
        ),
    ]
