# Generated by Django 4.1.2 on 2022-10-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("React", "0002_rename_userid_users_userid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users", old_name="Password", new_name="password",
        ),
        migrations.AlterField(
            model_name="photos",
            name="imgName",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="photos",
            name="imgSrc",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="users",
            name="userName",
            field=models.CharField(default="", max_length=100),
        ),
    ]
