# Generated by Django 4.1.2 on 2022-10-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("React", "0003_rename_password_users_password_alter_photos_imgname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users", old_name="userName", new_name="username",
        ),
        migrations.AlterModelTable(name="photos", table="photos",),
        migrations.AlterModelTable(name="users", table="users",),
    ]
