# Generated by Django 4.1.2 on 2022-10-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("React", "0004_rename_username_users_username_alter_photos_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("imagNAME", models.CharField(max_length=200)),
                ("rating", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Wallpaper",
            fields=[
                ("imgId", models.AutoField(primary_key=True, serialize=False)),
                ("imagNAME", models.CharField(max_length=200)),
                ("imagSRC", models.CharField(max_length=200)),
                ("imagTAGS", models.CharField(max_length=200)),
            ],
            options={"db_table": "images",},
        ),
    ]
