# Generated by Django 4.1.2 on 2022-10-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("React", "0005_rating_wallpaper"),
    ]

    operations = [
        migrations.AlterModelTable(name="rating", table="backend_rating",),
        migrations.AlterModelTable(name="users", table="backend_user",),
        migrations.AlterModelTable(name="wallpaper", table="backend_items",),
    ]
