# Generated by Django 4.1.2 on 2022-10-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("React", "0006_alter_rating_table_alter_users_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="rating", table=None,),
        migrations.AlterModelTable(name="users", table=None,),
    ]
