# Generated by Django 4.1.2 on 2022-10-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("React", "0007_alter_rating_table_alter_users_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("imagname", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(name="Photos",),
        migrations.RemoveField(model_name="users", name="userId",),
        migrations.AddField(
            model_name="rating", name="fav", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rating", name="like", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rating", name="rating", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="users", name="password", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="users", name="username", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="wallpaper",
            name="imgId",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(name="wallpaper", table=None,),
    ]
