# Generated by Django 4.1.2 on 2022-10-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("React", "0008_favorite_delete_photos_remove_users_userid_and_more"),
    ]

    operations = []
