# Generated by Django 4.1.2 on 2022-10-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("React", "0009_merge_20221030_1354"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_name", models.CharField(default="", max_length=200)),
                ("img_src", models.CharField(default="", max_length=200)),
                ("img_tags", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="favorite",
            name="imagname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="username",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="rating",
            name="imagNAME",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="rating",
            name="username",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="wallpaper",
            name="imagNAME",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="wallpaper",
            name="imagSRC",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="wallpaper",
            name="imagTAGS",
            field=models.CharField(default="", max_length=200),
        ),
    ]
